#!/bin/bash
amazon-linux-extras install docker java-openjdk11 -y
systemctl enable docker
service docker start
cp /home/ec2-user/.ssh/authorized_keys /root/.ssh/authorized_keys
chmod 0600 /root/.ssh/authorized_keys
chown root: /root/.ssh/authorized_keys
